//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projekt_bazy
{
    using System;
    using System.Collections.Generic;
    
    public partial class public_key_user
    {
        public int id_key { get; set; }
        public int id_user { get; set; }
        public string public_key { get; set; }
    
        public virtual users users { get; set; }
    }
}
