//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projekt_bazy
{
    using System;
    using System.Collections.Generic;
    
    public partial class room_key
    {
        public int id_room_key { get; set; }
        public Nullable<int> id_room { get; set; }
        public string symetric_key { get; set; }
    
        public virtual rooms rooms { get; set; }
    }
}
